// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// VerifySender is an autogenerated mock type for the verify.Sender type
type VerifySender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, destination
func (_m *VerifySender) Send(ctx context.Context, destination string) (string, error) {
	ret := _m.Called(ctx, destination)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, destination)
	} else {
		r0 = ret.String(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Check provides a mock function with given fields: ctx, requestID, code
func (_m *VerifySender) Check(ctx context.Context, requestID string, code string) error {
	ret := _m.Called(ctx, requestID, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, requestID, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVerifySender creates a new VerifySender. The cleanup function asserts the
// mocks' expectations were met when the test completes.
func NewVerifySender(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerifySender {
	m := &VerifySender{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
